version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/src:/app/src
      - ./api/migrations:/app/migrations
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:postgres@db:5432/postgres
      - IS_DOCKER=true
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api
    networks:
      - default

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge